### ISSUE TITLE
Block "Start" button if textures are missing/incorrect

### ISSUE THREAD

**Issue by TheRealDannyyy** [Inf4mouskid/Font-to-Image#3]
Disable the "Start" button if the following requirements aren't met:
- Fill texture; Outline texture; Font file missing
- Fill texture; Outline texture aren't 150x150 pixels

**Comment by JarheadHME** [comment]
I've just changed it to just pull from a default file for both fill (solid black) and outline (completely clear) instead, and to resize the images the user provides to 150x150 automatically (though may be good to look into _how much_ it antialiases it and give feedback on that)

**Comment by TheRealDannyyy** [comment]
I'd honestly recommend making it a requirement to use 150x150 instead of going through the effort to resize and do any additional checks for that.
